### PR TITLE
Change from starboard to trivy-operator

### PR DESCRIPTION
**Pull request by NissesSenap**
Starboard is no longer actively maintained and contains old k8s API versions so we have to change to trivy-operator before going over to k8s 1.25.

Solves: #706

Manual removal might be needed

```shell
# delete generated cr in all namespaces
kubectl delete vulnerabilityreports.aquasecurity.github.io --all --all-namespaces

helm uninstall starboard-operator -n starboard-operator
helm uninstall starboard-exporter -n starboard-operator
helm uninstall trivy -n starboard-operator
helm uninstall trivy-extras -n starboard-operator

# delete k8s yaml
k delete statefulsets.apps trivy -n starboard-operator
k delete pvc data-trivy-0 -n starboard-operator

# delete ns
k delete ns starboard-operator

# delete crd
k delete crd ciskubebenchreports.aquasecurity.github.io clusterconfigauditreports.aquasecurity.github.io clustervulnerabilityreports.aquasecurity.github.io configauditreports.aquasecurity.github.io kubehunterreports.aquasecurity.github.io vulnerabilityreports.aquasecurity.github.io
```

If you deleted the starboard-exporter before deleting all the vulnerabilityreports the finalizers will create issues for you.
This is solved by removing the finalizer in all the vulnerabilityReports

```shell
for ns in $(kubectl get ns -o jsonpath="{.items[*].metadata.name}");
do
  for vuln in $(kubectl get vulnerabilityReport -o jsonpath="{.items[*].metadata.name}" -n $ns);
  do
    kubectl patch vulnerabilityReport $vuln -n $ns -p '{"metadata":{"finalizers":[]}}' --type=merge
  done
done
```

Once I also had to run the following due to reasons.

```shell
tf state rm 'module.aks1_core.module.starboard_crd.kubectl_manifest.this'
tf state rm 'module.aks1_core.kubernetes_role_binding.starboard_reports'
tf state rm 'module.aks1_core.kubernetes_cluster_role.starboard_reports'
```

### CODE REVIEW

**Comment by NissesSenap** [comment]
TODO: 

- [X] Verify that the new trivy-operator creates metrics in AKS
- [ ] Verify that the new trivy-operator creates metrics in EKS
- [ ] Verify that the new config works with aadpodidentity in Azure
- [ ] Verify that the new config works with AWS IRSA

I also want to create a PR to upstream that makes it possible to set trivy-server solution.
This way we will have to manage one less helm chart and it also seems to contain a few nice config that we probably want.
Will do that tomorrow.

**Comment by NissesSenap** [comment]
Apparently trivy also supports redis now a days. It seems to be a cached backend mainly but I found issues that points to it helping out with errors like this:

```
"level":"error","ts":"2023-02-14T11:55:53Z","logger":"reconciler.scan job","msg":"Scan job container","job":"trivy/scan-vulnerabilityreport-68856f9c69","container":"create","status.reason":"Error","status.message":"2023-02-14T11:55:41.714Z\t\u001b[31mFATAL\u001b[0m\timage scan error: scan error: scan failed: failed analysis: unable to get missing layers: unable to fetch missing layers: twirp error internal: failed to do request: Post \"http://trivy.trivy.svc.cluster.local:4954/twirp/trivy.cache.v1.Cache/MissingBlobs\":  dial tcp 172.20.254.58:4954: connect: connection refused\n"
```

Another option could also be that my trivy server had lots to do during the inital starts and it would only create issues.

Anyway I think it's better that we do minor changes and currently ignore the redis functionality and get this merged first.

**Review by jimgus — APPROVED** [review]
LGTM

**Comment by NissesSenap** [comment]
For eks

```shell
 tf state rm 'module.eks2_core.module.starboard_crd.kubectl_manifest.this'
tf state rm 'module.eks2_core.kubernetes_role_binding.starboard_reports'
tf state rm 'module.eks2_core.kubernetes_cluster_role.starboard_reports'
```

**Pull request merged**
