### PR TITLE
BREAKING enable aks nodepool to set os_disk_type

### PR DESCRIPTION
**Pull request by NissesSenap**
The default nodepool OS disk type is Ephemeral in AKS. But terraform has not
changed this, to avoid breaking changes. The Ephemeral disk type
will decrease boot time.

### CODE REVIEW

**Comment by NissesSenap** [comment]
Getting funny errors:

```
│ Error: creating/updating Managed Kubernetes Cluster Node Pool "standard" (Resource Group "rg-dev-we-aks"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="VMCacheSizeTooSmall" Message="The virtual machine size Standard_D2ds_v5 has a cache size of 0 bytes, but the OS disk requires 64424509440 bytes. Use a VM size with larger cache or disable ephemeral OS."
│ 
│   with module.aks1.azurerm_kubernetes_cluster_node_pool.this["standard"],
│   on .terraform/modules/aks1/modules/azure/aks/aks.tf line 74, in resource "azurerm_kubernetes_cluster_node_pool" "this":
│   74: resource "azurerm_kubernetes_cluster_node_pool" "this" {
```

**Comment by NissesSenap** [comment]
This is how it looks if you try to add to much os disk compared to what the node type supports.

```shell
│ Error: creating/updating Managed Kubernetes Cluster Node Pool "standard" (Resource Group "rg-dev-we-aks"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="VMCacheSizeTooSmall" Message="The virtual machine size Standard_D2ds_v4 has a cache size of 53687091200 bytes, but the OS disk requires 64424509440 bytes. Use a VM size with larger cache or disable ephemeral OS."
│ 
│   with module.aks1.azurerm_kubernetes_cluster_node_pool.this["standard"],
│   on .terraform/modules/aks1/modules/azure/aks/aks.tf line 74, in resource "azurerm_kubernetes_cluster_node_pool" "this":
│   74: resource "azurerm_kubernetes_cluster_node_pool" "this" {
│ 
╵
make: *** [Makefile:80: apply] Error 1
```

**Comment by NissesSenap** [comment]
Below you can find examples of how to keep on using the module without changing any of your node pools.

This by setting `os_disk_type =  "Managed"` and `os_disk_size_gb = null`
You will also find a example on how to use Ephemeral disk.

```.hcl
  additional_node_pools = [
    {
      name                 = "standard2"
      orchestrator_version = "1.21.2"
      vm_size              = "Standard_D2s_v5"
      min_count            = 1
      max_count            = 3
      node_labels          = {}
      node_taints          = []
      os_disk_type         = "Managed"
      os_disk_size_gb      = null
      spot_enabled         = false
      spot_max_price       = null
    },
    {
      name                 = "standard"
      orchestrator_version = "1.21.2"
      vm_size              = "Standard_D2ds_v4"
      min_count            = 1
      max_count            = 3
      node_labels          = {}
      node_taints          = []
      os_disk_type         = "Ephemeral"
      os_disk_size_gb      = 60
      spot_enabled         = false
      spot_max_price       = null
    },
```

We will provide more documentation around this during the coming week.

**Review by phillebaba — APPROVED** [review]
LGTM. We will come back at a later time and set some default values after testing this feature a bit more.

**Pull request merged**
