### PR TITLE
Change ACR SKU to Standard

### PR DESCRIPTION
**Pull request by phillebaba**
This sets all ACR SKUs to Premium. I do not see a point in running a Basic SKU as Premium includes a lot more storage. Plus the increased bandwidth does not hurt.

### CODE REVIEW

**Comment by NissesSenap** [comment]
Will this recreate the acr or not when upgrading?
How much is the process difference?
I think it's a good idea, this provides oci compatibility as well so we can store helm charts and other fun stuff in acr.

**Comment by jimgus** [comment]
Agree with above comment, it would be good to know if there are any upgrade impacts or not

**Comment by phillebaba** [comment]
Sorry this was actually meant to be Standard and not Premium. Changing the SKU has no affect more than it just changing.

**Basic**
> A cost-optimized entry point for developers learning about Azure Container Registry. Basic registries have the same programmatic capabilities as Standard and Premium (such as Azure Active Directory authentication integration, image deletion, and webhooks). However, the included storage and image throughput are most appropriate for lower usage scenarios.

**Standard**
> Standard registries offer the same capabilities as Basic, with increased included storage and image throughput. Standard registries should satisfy the needs of most production scenarios.


https://learn.microsoft.com/en-us/azure/container-registry/container-registry-skus

Reading this it is reasonable that we should be using Standard and not Basic.

**Comment by NissesSenap** [comment]
Looking at the pricing it seems like a no brainer as well.
https://azure.microsoft.com/en-us/pricing/details/container-registry/

**Review by NissesSenap — APPROVED** [review]

**Pull request merged**
