### PR TITLE
Replaced misspelled variable kube_state_metrics_namepsaces

### PR DESCRIPTION
**Pull request by marulkan**
kube_state_metrics_namepsaces were replaced with kube_state_metrics_namespaces
This could potentially cause issues with tfvar files that are configuring the misspelled variable, since these will have to be updated as well.

### CODE REVIEW

**Comment by simongottschlag** [comment]
Hi @marulkan and thank you for the PR! 🥇

Would it be possible to remove the modification of the changelog and add a new entry for in it unreleased -> fixed?

I want @phillebaba and @NissesSenap to take a look at this change as well before approving.

**Comment by marulkan** [comment]
Certainly, I'll have a look at cleaning it up at bit on monday.

**Review by NissesSenap — DISMISSED** [review]
LGTM
Thanks allot @marulkan

**Comment by phillebaba** [comment]
@marulkan could you please rebase from main. This fixes the changelog checker.

**Review by NissesSenap — APPROVED** [review]

**Pull request merged**
