### PR TITLE
Add config for AKS automatic_channel_upgrade & upgrade_settings

### PR DESCRIPTION
**Pull request by CalleB3**
Adding configuration for AKS 
automatic_channel_upgrade & upgrade_settings configuration in terraform-modules.
Implementing to simplify and automate the updating / upgrading process for K8s clusters.

### CODE REVIEW

**Comment by NissesSenap** [comment]
@simongottschlag @phillebaba do you have any thoughts on this one?
I think this PR should do the trick.

**Comment by CalleB3** [comment]
To be backwards compatible and able to run without "automatic_channel_upgrade" set variable to "null".
 "aks_upgrade_channel = null"

Here is the different channels you can use.
https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel-preview
Could recommend using "node-image" to patch the nodes automatically.

**Review by NissesSenap — APPROVED** [review]

**Review by ahockersten — APPROVED** [review]
LGTM

**Comment by phillebaba** [comment]
The max surge setting is a good option, as right now it will do a single node at a time. 

I am not too convinced about the automatic upgrade channel. My personal opinion is that we should not enable it. But if we are going to enable it, then it should not be a variable but a hard coded setting that we use everywhere. I do not want the possibility of different behaviors in different clusters.

**Comment by NissesSenap** [comment]
Me and @phillebaba discussed a bit and setting "node-image" as the default value could be an option.

@CalleB3 is there any information from azure how these node-images gets updated on the nodes?
Preferably we would want to make sure that all the clusters don't start to changing nodes at the same times.
Even better would be if we could get them to split it with a certain delay in prod after all of dev is done, like a few days.

I don't think these options exist now but do they have some docs that might explain how "node-image" works?

**Comment by CalleB3** [comment]
> Me and @phillebaba discussed a bit and setting "node-image" as the default value could be an option.
> 
> @CalleB3 is there any information from azure how these node-images gets updated on the nodes? Preferably we would want to make sure that all the clusters don't start to changing nodes at the same times. Even better would be if we could get them to split it with a certain delay in prod after all of dev is done, like a few days.
> 
> I don't think these options exist now but do they have some docs that might explain how "node-image" works?

I found this:
https://docs.microsoft.com/en-us/azure/aks/planned-maintenance
&
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/maintenance_configuration
Where you can use automatic upgrade and only allow them to perform during set maintenance windows.
Not entirely sure on how the config would look but should be considerable.

**Comment by NissesSenap** [comment]
Found https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#maintenance_window I think this sounds like a good option. I assume that this would apply to all the nodes in the cluster but I don't know. We would have to try this out.
@phillebaba do you think this could be a possible way forward?

**Comment by phillebaba** [comment]
I still dont really agree with this. I would not be comfortable doing this in the middle of the night automatically right now. Then again if everyone else wants to I am not going to block it.

**Comment by NissesSenap** [comment]
I see your point, this is a feature that we can add in the future.
For now we close it. Thanks for your work on this @CalleB3

**Pull request closed without merging**
