### PR TITLE
Drop CAP_SYS_ADMIN in default constraints

### PR DESCRIPTION
**Pull request by NissesSenap**
Drop CAP_SYS_ADMIN from all containers in the cluster just like NET_RAW.
Update grafana-library to version 0.10.0.

### CODE REVIEW

**Comment by NissesSenap** [comment]
From seccomp gatekeeper-libary docs:

```.txt
            allowedProfiles:
              type: array
              description: >-
                An array of allowed profile values for seccomp on Pods/Containers.

                Can use the annotation naming scheme: `runtime/default`, `docker/default`, `unconfined` and/or
                `localhost/some-profile.json`. The item `localhost/*` will allow any localhost based profile.

                Can also use the securityContext naming scheme: `RuntimeDefault`, `Unconfined`
                and/or `Localhost`. For securityContext `Localhost`, use the parameter `allowedLocalhostProfiles`
                to list the allowed profile JSON files.

                The policy code will translate between the two schemes so it is not necessary to use both.

                Putting a `*` in this array allows all Profiles to be used.

                This field is required since with an empty list this policy will block all workloads.
              items:
                type: string
            allowedLocalhostFiles:
              type: array
              description: >-
                When using securityContext naming scheme for seccomp and including `Localhost` this array holds
                the allowed profile JSON files.

                Putting a `*` in this array will allows all JSON files to be used.

                This field is required to allow `Localhost` in securityContext as with an empty list it will block.
```

**Comment by NissesSenap** [comment]
https://github.com/XenitAB/terraform-modules/pull/576 needs to be merged before this one got a chance.
Need to update CRD versions.

**Comment by NissesSenap** [comment]
Don't know why I did it but seccomp should be done in a separate PR.

```
    {
      kind               = "K8sPSPSeccomp"
      name               = "psp-capabilities"
      enforcement_action = ""
      match = {
        kinds      = []
        namespaces = []
      }
      parameters = {
        allowedProfiles       = ["*"]
        allowedLocalhostFiles = ["*"]
      }
    },
```

**Comment by NissesSenap** [comment]
Don't know why I did it but seccomp should be done in a separate PR.

```
    {
      kind               = "K8sPSPSeccomp"
      name               = "psp-capabilities"
      enforcement_action = ""
      match = {
        kinds      = []
        namespaces = []
      }
      parameters = {
        allowedProfiles       = ["*"]
        allowedLocalhostFiles = ["*"]
      }
    },
```

**Review by phillebaba — APPROVED** [review]
LGTM

**Pull request merged**
